Repository DeveloperAcademy-POSTECH/toGather, pull requests merged in 2022-08, with the labels that each got.

#135 [Docs] 리드미 수정
  License
  README.md
Labels: ⚙️Setting

#130 [FEAT] 친구추가뷰 쪼개기, 친구추가 FirebaseManager 함수수정
  .github/pull_request_template.md
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/RGBColorInProgressCircle.swift
  ToGather/ToGather/Screens/Core/Main/View/MainView.swift
  ToGather/ToGather/Screens/Core/Main/ViewModel/MainViewModel.swift
  ToGather/ToGather/Screens/Core/Start/View/StartView.swift
  ToGather/ToGather/Screens/Core/Start/ViewModel/OnboardingViewModel.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/PinStackView.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/ViewModel/FriendAdditionViewModel.swift
  ToGather/ToGather/Screens/Onboarding/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: 🛠Logic

#140 [FEAT] Friend데이터 비동기 처리
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Extension/Sequence+Extension.swift
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Screens/Core/Main/View/MainView.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: 📒 Firebase, 🛠Logic

#142 [Feat] 금액 표시 문구 변경
  ToGather/ToGather/Screens/Onboarding/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/Onboarding/SettingPeriod/SettingPeriod.swift
Labels: 💡Feat

#146 [CHORE] UserViewModel, FriendAdditionView 및 ViewModel 코드 리팩토링
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Screens/Onboarding/FriendAddition/UIComponent/PersonView.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/AlreadyAddedFriendView.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/ViewModel/FriendAdditionViewModel.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: ⚙️Setting

#148 [CHORE] 환경세팅창에서 닉네임을 고유아이디로 변경
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Screens/Core/Setting/View/SettingView.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: ⚙️Setting

#150 [CHORE] 컬러설정 통일
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Literal/ColorAsset.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/AlreadyAddedFriendView.swift
  ToGather/ToGather/Screens/Onboarding/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/Onboarding/SettingPeriod/SettingPeriod.swift
Labels: 🏞 UI

#155 [CHORE] Appstorage 추가 및 OnBoardingViewModel 삭제
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Screens/Core/Main/View/MainView.swift
  ToGather/ToGather/Screens/Core/Start/View/StartView.swift
  ToGather/ToGather/Screens/Core/Start/ViewModel/OnboardingViewModel.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/Onboarding/GoalSetting/View/GoalSetting.swift
  ToGather/ToGather/Screens/Onboarding/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/Onboarding/SettingPeriod/SettingPeriod.swift
Labels: 🛠Logic

#153 [Feat] 친구에게 알리기 제거
  ToGather/ToGather/Screens/Core/SavingRecord/View/SavingRecordView.swift
Labels: 💡Feat

#151 [Feat] 더미데이터 수정 & 더미데이터를 인자로 받는 경우를 수정
  ToGather/ToGather/Global/Logic/TimeLogic.swift
  ToGather/ToGather/Models/DummyData.swift
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/FriendProgressCircle.swift
  ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/MyProgressCircle.swift
  ToGather/ToGather/Screens/Core/Main/UIComponent/ProgressCircle/ProgressCircle.swift
  ToGather/ToGather/Screens/Core/Main/ViewModel/MainViewModel.swift
  ToGather/ToGather/Screens/Core/SavingStatus/View/SavingStatusView.swift
  ToGather/ToGather/Screens/Core/mainFriendSaving/FrSavingView.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: 💡Feat

#156 [FEAT] 상세 저축현황시 나의 저축성공사진 데이터 보기
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Models/ThisWeek.swift
  ToGather/ToGather/Screens/Core/SavingRecord/View/SavingRecordView.swift
  ToGather/ToGather/Screens/Core/SavingStatus/View/SavingStatusView.swift
  ToGather/ToGather/Screens/Core/Start/ViewModel/OnboardingViewModel.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: 💡Feat

#158 [Feat] 저축다시하기 기능구현
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Screens/Core/Main/View/MainView.swift
  ToGather/ToGather/Screens/Core/SavingStatus/View/SavingStatusView.swift
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: 💡Feat

#161 [Fix] 빌드오류 해결
  ToGather/ToGather/Screens/Onboarding/FriendAddition/UIComponent/PersonView.swift
  ToGather/ToGather/Screens/Onboarding/FriendAddition/View/FriendAdditionView.swift
Labels: 🐞 Bug

#162 [fix] 빌드오류 해결
  ToGather/ToGather/ViewModels/UserViewModel.swift
Labels: 🐞 Bug
