Repository DeveloperAcademy-POSTECH/toGather, pull requests merged in 2022-07, with the labels that each got.

#103 [Feat] 파이어베이스 이미지 가져오기 함수
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
Labels: 🍏 Miller, Logic

#105 [Fix] 시간 로직 수정 & 모델 연결
  ToGather/ToGather/Global/Service/TimeLogic.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Models/ThisWeek.swift
  ToGather/ToGather/Screens/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/ProgressCircle/DummyData.swift
  ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
  ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift
  ToGather/ToGather/Screens/mainFriendSaving/FrSavingView.swift
Labels: 🍏 Lance, 🏞 UI, Logic

#116 네비게이션 뷰에 custom 백버튼을 적용
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Service/CustomNavigationLink.swift
  ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/GoalSetting/View/GoalSetting.swift
  ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift
Labels: 🏞 UI

#117 친구추가 뷰모델 생성 및 자연스러운 애니메이션
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Screens/FriendAddition/View/AlreadyAddedFriendView.swift
  ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/FriendAddition/ViewModel/FriendAdditionViewModel.swift
Labels: 🍏 Neal, Logic

#129 [Feat] 온보딩에서 선택하지 않을 경우 다음 버튼 비활성화
  ToGather/ToGather/Screens/GoalSetting/View/GoalSetting.swift
  ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift
Labels: 🏞 UI
