Repository DeveloperAcademy-POSTECH/toGather, pull requests merged in 2022-06, with the labels that each got.

#4 [ADD] Project setting - Data Structure
  ToGather/Extension/Color+Extension.swift
  ToGather/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  ToGather/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  ToGather/Resource/Assets.xcassets/Contents.json
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Product.swift
  ToGather/ToGather/Saving.swift
  ToGather/ToGather/Screens/ContentView.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
  ToGather/ToGather/ThisWeek.swift
  ToGather/ToGather/User.swift
Labels: 🍏 Miller

#8 [Add] gitattributes
  .gitattributes
  ToGather/ToGather/Product.swift
Labels: 🍏 Miller

#9 [ADD] Model-Setting
  .github/pull_request_template.md
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Models/Product.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Models/ThisWeek.swift
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Models/modelempty.swift
Labels: 🍏 Miller, ◾️ Setting

#13 [ADD] Add firebaseStorage package
  ToGather/ToGather.xcodeproj/project.pbxproj
Labels: 🍏 Eve, 📒 Firebase

#20 [ADD] Add SwiftUI-Introspect package
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🍏 Neal, ◾️ Setting

#25 [FEAT] MainView combine with progressCircle
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Extension/Color+Extension.swift
  ToGather/ToGather/Global/Resources/Assets.xcassets/Imac.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/Ipad.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/Ipad.imageset/Ipad.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/Iphone.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/Iphone.imageset/Iphone.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/Macbook.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/Macbook.imageset/Macbook.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/imac.imageset/imac.png
  ToGather/ToGather/Models/Product.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/Main/ViewModel/MainViewModel.swift
  ToGather/ToGather/Screens/ProgressCircle/DummyData.swift
  ToGather/ToGather/Screens/ProgressCircle/FriendsProgressCircle.swift
  ToGather/ToGather/Screens/ProgressCircle/MyProgressCircle.swift
  ToGather/ToGather/Screens/ProgressCircle/ProgressCircle.swift
  ToGather/ToGather/Screens/ProgressCircle/RGBColorInProgressCircle.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Miller, 🏞 UI

#27 [Chore] ZStack & VStack delete
  ToGather/ToGather/Screens/Main/View/MainView.swift
Labels: 🍏 Miller, 🏞 UI

#40 [FIX] .swiftlint.yml 추가
  ToGather/.swiftlint.yml
  ToGather/ToGather.xcodeproj/project.pbxproj
Labels: 🍏 Eve, ◾️ Setting

#43 [Fix] 폴더 레퍼런스에 의한 컴파일 에러 해결 #42
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🍏 Neal, 🐞 Bug

#39 생성한 settingPeriod 뷰 new-dev에 머지하기
  ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift
Labels: 🍏 Lance, 🏞 UI

#38 [FEAT] Mainview FriendAddedButton UI & Logic
  .github/pull_request_template.md
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Resources/Assets.xcassets/test.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/test.imageset/test.png
  ToGather/ToGather/Global/UIComponent/CustomProgressBar.swift
  ToGather/ToGather/Global/UIComponent/SwiftUIView3.swift
  ToGather/ToGather/Models/Notification.swift
  ToGather/ToGather/Models/Product.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/Main/ViewModel/MainViewModel.swift
  ToGather/ToGather/Screens/Notifications/View/NotificaionCell.swift
  ToGather/ToGather/Screens/Notifications/View/NotificationsView.swift
  ToGather/ToGather/Screens/ProgressCircle/AddedCircleView.swift
  ToGather/ToGather/Screens/ProgressCircle/DummyData.swift
  ToGather/ToGather/Screens/ProgressCircle/FriendsProgressCircle.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Miller, 🏞 UI

#53 [FEAT] 온보딩 첫 페이지 목표 설정 뷰
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-airpod.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-airpod.imageset/goal-airpod@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-applewatch.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-applewatch.imageset/goal-applewatch@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-imac.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-imac.imageset/goal-imac@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-ipad.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-ipad.imageset/goal-ipad@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-iphone.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-iphone.imageset/goal-iphone@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-air.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-air.imageset/goal-macbook-air@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-pro.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-pro.imageset/goal-macbook-pro@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macmini.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macmini.imageset/goal-macmini@3x.png
  ToGather/ToGather/Models/ItemData.swift
  ToGather/ToGather/Screens/GoalSetting/View/GoalItem.swift
  ToGather/ToGather/Screens/GoalSetting/View/GoalSetting.swift
  ToGather/ToGather/Screens/GoalSetting/View/GoalSettingTitleView.swift
Labels: 🍏 Bit, 🏞 UI

#46 [FEAT] 온보딩 마지막 페이지 추가
  ToGather/.swiftlint.yml
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Literal/ColorAsset.swift
  ToGather/ToGather/Global/Service/OnboardingViewModel.swift
  ToGather/ToGather/Global/Service/SwiftUIView.swift
  ToGather/ToGather/Global/UIComponent/SwiftUIView3.swift
  ToGather/ToGather/Models/Product.swift
  ToGather/ToGather/Models/ThisWeek.swift
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Screens/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/LastOnboarding/ViewModel/LastOnboardingViewModel.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Eve, 🏞 UI, 📒 Firebase

#71 [ADD]앱 아이콘 추가
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🍏 Max

#73 [Feat] 알림기능구현
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Extension/Color+Extension.swift
  ToGather/ToGather/Global/Extension/UserDefaults+Extension.swift
  ToGather/ToGather/Global/Literal/Constants.swift
  ToGather/ToGather/Global/UIComponent/CustomProgressBar.swift
  ToGather/ToGather/Models/Notification.swift
  ToGather/ToGather/Models/Product.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Models/ThisWeek.swift
  ToGather/ToGather/Models/User.swift
  ToGather/ToGather/Screens/FriendAddition/View/AlreadyAddedFriendView.swift
  ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/Main/ViewModel/MainViewModel.swift
  ToGather/ToGather/Screens/Notifications/View/NotificaionCell.swift
  ToGather/ToGather/Screens/Notifications/View/NotificationsView.swift
  ToGather/ToGather/Screens/Notifications/ViewModel/NotificationsViewModel.swift
  ToGather/ToGather/Screens/ProgressCircle/AddedCircleView.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Miller, 🏞 UI, Logic

#74 [FIX] 중복된 상품 이미지 정리
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-airpod.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-airpod.imageset/goal-airpod@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-applewatch.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-applewatch.imageset/goal-applewatch@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-imac.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-imac.imageset/goal-imac@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-ipad.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-ipad.imageset/goal-ipad@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-iphone.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-iphone.imageset/goal-iphone@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-air.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-pro.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macbook-pro.imageset/goal-macbook-pro@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macmini.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goal-macmini.imageset/goal-macmini@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/airpodsPro.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/airpodsPro.imageset/airpods pro.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/airpodsPro.imageset/airpods pro@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/airpodsPro.imageset/airpods pro@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/appleWatch.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/appleWatch.imageset/appleWatch.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/appleWatch.imageset/appleWatch@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/appleWatch.imageset/appleWatch@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iPadmini.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iPadmini.imageset/iPadmini.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iPadmini.imageset/iPadmini@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iPadmini.imageset/iPadmini@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/imac.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/imac.imageset/imac.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/imac.imageset/imac@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/imac.imageset/imac@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iphone13.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iphone13.imageset/iphone13.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iphone13.imageset/iphone13@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/iphone13.imageset/iphone13@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macStudio.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macStudio.imageset/macStudio.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macStudio.imageset/macStudio@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macStudio.imageset/macStudio@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbook.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbook.imageset/macbook.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbook.imageset/macbook@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbook.imageset/macbook@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbookPro.imageset/Contents.json
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbookPro.imageset/macbook Pro.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbookPro.imageset/macbook Pro@2x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/goalProduct/macbookPro.imageset/macbook Pro@3x.png
  ToGather/ToGather/Global/Resources/Assets.xcassets/macbook.imageset/macbook@3x.png
  ToGather/ToGather/Models/ItemData.swift
Labels: 🍏 Bit, 🐞 Bug

#76 [FEAT] 저축 기록화면 UI
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
Labels: 🍏 Bit, 🏞 UI

#77 Saving struct 객체 수정
  ToGather/ToGather/Global/Service/TimeLogic.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Screens/ProgressCircle/DummyData.swift
Labels: 🍏 Lance, Logic

#85 [FEAT] 설정창 UI & 기능구현
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Extension/Color+Extension.swift
  ToGather/ToGather/Global/Literal/Constants.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Global/UIComponent/CheckboxToggleStyle.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/Setting/View/DisplayModeView.swift
  ToGather/ToGather/Screens/Setting/View/SettingView.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Miller, 🏞 UI

#82 [Feat] 메인뷰에 userViewModel 연결하기 & 하드코딩된 부분 수정하기
  ToGather/ToGather/Global/Service/MoneyLogic.swift
  ToGather/ToGather/Global/Service/TimeLogic.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
  ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Lance

#88 [feat] 간단한 UI 수정
  ToGather/ToGather/Screens/ProgressCircle/MyProgressCircle.swift
  ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift
Labels: 🍏 Lance

#87 저축 기록화면 - 사진 불러오기 및 사진 존재 여부에 따른 제어
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather.xcodeproj/xcshareddata/xcschemes/ToGather.xcscheme
  ToGather/ToGather/Screens/SavingRecord/View/ImagePicker.swift
  ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
Labels: 🍏 Bit, Logic

#89 [feat] 저축 기록화면, 친구 상세페이지 네비게이션 연결
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/Main/ViewModel/MainViewModel.swift
  ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
  ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift
Labels: 🍏 Lance

#90 [Feat] 온보딩뷰 전체 연결
  .DS_Store
  ToGather/ToGather.xcodeproj/project.pbxproj
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Models/Product.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Screens/FriendAddition/View/AlreadyAddedFriendView.swift
  ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/FriendAddition/View/PinStackView.swift
  ToGather/ToGather/Screens/GoalSetting/View/GoalSetting.swift
  ToGather/ToGather/Screens/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift
  ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift
  ToGather/ToGather/Screens/Start/View/StartView.swift
  ToGather/ToGather/Screens/Start/ViewModel/OnboardingViewModel.swift
  ToGather/ToGather/Screens/ToGatherApp.swift
Labels: 🍏 Neal, 🏞 UI, 디자인

#92 [Fix] Navigation back 버튼 안보이는 현상 수정
  ToGather/ToGather/Screens/FriendAddition/View/FriendAdditionView.swift
  ToGather/ToGather/Screens/SettingPeriod/SettingPeriod.swift
Labels: 🍏 Neal, 🐞 Bug

#94 [Fix] startDate 로직 수정
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Models/Saving.swift
  ToGather/ToGather/Screens/LastOnboarding/View/LastOnboardingView.swift
Labels: 🍏 Eve

#98 [Fix] 맞은 아이디 grid shaking 버그 수정
  ToGather/ToGather/Screens/FriendAddition/View/PinStackView.swift
Labels: 🍏 Neal, 🏞 UI, 🐞 Bug

#95 Feat/notification dummy
  .DS_Store
  ToGather/ToGather/Screens/Notifications/ViewModel/NotificationsViewModel.swift
Labels: 🍏 Miller

#100 Feat/upload image
  ToGather/ToGather/Global/Service/FirebaseManager.swift
  ToGather/ToGather/Global/Service/UserViewModel.swift
  ToGather/ToGather/Screens/LastOnboarding/View/LastOnboardingView.swift
  ToGather/ToGather/Screens/Main/View/MainView.swift
  ToGather/ToGather/Screens/SavingRecord/View/SavingRecordView.swift
Labels: 🍏 Miller

#101 [Feat] 상세저축 페이지 수정
  ToGather/ToGather/Screens/SavingStatus/View/SavingStatusView.swift
Labels: 🍏 Neal
